### PR TITLE
Avoid resolving the promise if the callback event is canceled

### PR DESCRIPTION
**Pull request by yankarinRG**
Now the following code will be valid:
```
let options = {
    title: null,
    body: '... custom html input ...',
    okButton: {
        label: 'Save',
        style: 'success',
        close: false,
        callback: (event, modal) => {
            if (isCustomInputValid()) {
                // hide the dialog, resolve the promise, and do something with the input
                modal.hide();
            } else {
                // keep the dialog open and don't resolve the promise
                event.preventDefault();
            }
        }
    },
    closeButton: {
        label: 'Close',
        style: 'danger'
    },
    size: 'lg',
    center: true,
    swapButtonOrder: true
};

try {
    await modbox.confirm(options);
} catch (e) {
    // Close button was clicked
    return;
}

// do something with the custom input
```

### CODE REVIEW

**Comment by erobertson42** [comment]
Thank you. I'll take a look as soon as I get a chance.

**Comment by erobertson42** [comment]
This was a good idea.  Thank you for taking the time to create a pull request.  I've merged this into release [v1.6.2](https://github.com/erobertson42/bootstrap-modbox/releases/tag/v1.6.2).

**Comment by yankarinRG** [comment]
Thank you, I needed it and thought it could be useful for everyone. 😊
Since I have not given a too thorough check, is this CR extendable to the other buttons? Or is it ok that only the OK button has this new behavior?

**Comment by erobertson42** [comment]
It's only the `okButton`.  I don't see that it would make much logical sense for the `closeButton`, and modals created by calling the constructor don't use a Promise, so there's no point with custom buttons either.

**Comment by yankarinRG** [comment]
If so then it's even better! I think we can consider this CR finished and no longer partial.

**Pull request merged**
